### ISSUE TITLE
Create User table and database

### ISSUE THREAD

**Issue by sbaljeet13** [ChristianChidiac/harmonIQ#4]
- [x] #16
- [ ] Add Quiz table
- [ ] Table/column to store user's scores

**Comment by mononomori** [comment]
I created a new branch based on main for working on the user-table database. Only worked on the User class and a controller to populate the table with OAuthentication info (current @getmapping and return are just placeholders). I'm not sure if the token properties in class will be necessary.

**Comment by sbaljeet13** [comment]
Outdated. Design changed for Admin view and Users table
