### ISSUE TITLE
Display Quiz Count on User Profile

### ISSUE THREAD

**Issue by sbaljeet13** [ChristianChidiac/harmonIQ#67]
User View, Quiz Count (Iteration 3) [Story Points: 3] - A user would like to see their total quizzes played count to increase after they play a quiz.
Has the user viewed their profile and checked their Quiz Count?
-> True: The user navigates to the quiz page, plays any of the available quizzes, then returns to their profile.
-> False: The user navigates to their profile to make note of their current Quiz Count then navigates to the quiz page, plays any of the available quizzes, then returns to their profile.
The user sees that the Quiz Count integer has increased by 1.

**Comment by mononomori** [comment]
Closed with #87
