### ISSUE TITLE
Design Collaborative Playlist UI

### ISSUE THREAD

**Issue by sbaljeet13** [ChristianChidiac/harmonIQ#69]
Design a UI for the following feature:

Collaborative Playlist (Iteration 2) [Story Points: 13] - The user clicks the collaborative playlist menu item and is redirected to the collaborative playlist page where the playlist is displayed.
Does the user want to join the playlist as a collaborator in order to add songs to the playlist?
-> True: The user’s Spotify account is added to the playlist as a collaborator, and they are now able to add songs to the playlist by voting for them.
-> False: The user is not added to the playlist as a collaborator, and they are redirected back to the home page.

**Comment by michellepark53** [comment]
![Image](https://github.com/user-attachments/assets/152f16dc-ddcd-40a0-bb86-d7f793d8810a)

**Main Playlist Page**

Features:
- When the three dots are clicked, edit options are shown: add songs, delete songs, and create a playlist
- Create a playlist: It lets you create a Spotify playlist directly by clicking, which will open Spotify and show the created playlist. Check out Whisperify's feature.

- If you hover over the album art, it lets you play a song for a short moment, just like in the song recognition quiz
- It also shows who added the song by displaying their profile picture in the upper right corner when hovered over
- Profile pics of collaborators; their names will be displayed when hovered over

**Comment by michellepark53** [comment]
![Image](https://github.com/user-attachments/assets/06917be5-045a-41b8-b5a3-c339d93f7306)

**Add Songs**

Features:

- When hovered over, it highlights the selection and the + icon for adding songs appears, just like on Spotify
- A check mark appears for already added songs
- The add song feature will appear in a pop-up, not on a separate page

**Comment by michellepark53** [comment]
![Image](https://github.com/user-attachments/assets/69991c78-11b6-44dc-83e9-da150d8f146b)

**Add Songs - At Max**

Features:

- When the playlist already has the maximum number of songs
- When the user clicks anywhere outside the pop-up, it will disappear

**Comment by michellepark53** [comment]
![Image](https://github.com/user-attachments/assets/48c6894f-c63d-4284-8504-e49cad1733fd)

**Delete Songs**

Features:

- When the delete button is clicked, the playlist page enters a deletable state
- A trashcan icon appears when hovering over the album image; clicking this icon will delete the song. 
- Once the user has finished deleting songs and clicks the 'Done' button, the playlist returns to its original state.
